'''
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''
from math import factorial
from math import sqrt

def T(n):
    return n*(n+1)/2

def nd(x):
    '''
    Returns the number of divisors that a number has.
    '''
    n=2
    for d in range(2,int(sqrt(x)+1)):
        if x%d==0:
            n+=2
    if sqrt(x).is_integer():
        n-=1
    return n

n=10000
while nd(T(n))<=500:
    n+=1
print(T(n))
